version: "3.6"
services:
  app:
    image: hungnq/nodejs-docker
    environment:
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    ports:
      - "4040:4040"
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes: 
      - .docker/data/db:/data/db
    restart: unless-stopped
